---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
  Api:
    OpenApiVersion: '3.0.2'
Parameters:
  HTTPResponse:
    Type: Number
    Default: 302
    AllowedValues: [301, 302]
    Description: "The HTTP response status code."
  NewDomain:
    Type: String
    Description: "New domain to redirect to."
Resources:
  GetFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: "Handles GET requests."
      Handler: get.handler
      Runtime: nodejs12.x
      CodeUri: ./lambda
      Environment:
        Variables:
          NEW_DOMAIN: "https://www.amazon.com"
          HTTP_RESPONSE: 301
      Events:
        GetProxy:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: get
        GetCustom:
          Type: Api
          Properties:
            Path: /
            Method: get
#  AnyFunction:
#    Type: AWS::Serverless::Function
#    Properties:
#      Description: "Handles everything except GET requests."
#      Handler: any.handler
#      Runtime: nodejs12.x
#      CodeUri: ./lambda
#      Environment:
#        Variables:
#          NEW_DOMAIN: !Ref NewDomain
#          HTTP_RESPONSE: !Ref HTTPResponse
#      Events:
#        AnyProxy:
#          Type: Api
#          Properties:
#            Path: /{proxy+}
#            Method: any
#        AnyCustom:
#          Type: Api
#          Properties:
#            Path: /
#            Method: any
Outputs:
    apiGatewayConsoleDashboardUrl:
        Value: !Sub " https://console.aws.amazon.com/apigateway/home?region=${AWS::Region}#/apis/${ServerlessRestApi}/dashboard"

    redirectorInvokeUrl:
        Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/"

    
